export type Envelope<T> = {
  success: boolean;
  data: T | null;
  error: { code: string; message: string; details?: Record<string, string[]> } | null;
  requestId: string;
  page?: number;
  pageSize?: number;
  total?: number;
};

export type ArticleListItem = {
  id: string;
  title: string;
  slug: string;
  excerpt: string;
  status: string;
  publishedAt: string | null;
  createdAt: string;
  updatedAt: string;
  readingTimeMinutes: number;
  viewCount: number;
  isFeatured: boolean;
  isAiGenerated: boolean;
  categoryName: string;
  categorySlug: string;
  authorName: string;
  authorSlug: string;
  featuredImageUrl: string | null;
  tags: string[];
  technologies: string[];
  difficulty: string;
  contentType: string;
};

export type TocItem = { level: number; text: string; id: string };
export type TagRef = { id: string; name: string; slug: string };
export type ArticleNav = { id: string; title: string; slug: string };
export type SeriesPart = { id: string; title: string; slug: string; order: number; isCurrent: boolean; isPublished: boolean };

export type ArticleDetail = {
  id: string;
  title: string;
  slug: string;
  subtitle: string | null;
  excerpt: string;
  content: string;
  contentFormat: string;
  status: string;
  publishedAt: string | null;
  scheduledAt: string | null;
  createdAt: string;
  updatedAt: string;
  featuredImageId: string | null;
  featuredImageUrl: string | null;
  thumbnailImageId: string | null;
  canonicalUrl: string | null;
  metaTitle: string | null;
  metaDescription: string | null;
  ogTitle: string | null;
  ogDescription: string | null;
  ogImage: string | null;
  readingTimeMinutes: number;
  viewCount: number;
  isFeatured: boolean;
  isAiGenerated: boolean;
  authorId: string;
  authorName: string;
  authorSlug: string;
  authorBio: string | null;
  authorAvatarUrl: string | null;
  authorGitHub: string | null;
  authorLinkedIn: string | null;
  authorX: string | null;
  authorWebsite: string | null;
  categoryId: string;
  categoryName: string;
  categorySlug: string;
  seriesId: string | null;
  seriesName: string | null;
  seriesSlug: string | null;
  seriesOrder: number | null;
  difficulty: string;
  contentType: string;
  rejectionReason: string | null;
  rowVersion: number;
  tags: TagRef[];
  technologies: TagRef[];
  tableOfContents: TocItem[];
  related: ArticleListItem[];
  previous: ArticleNav | null;
  next: ArticleNav | null;
  seriesParts: SeriesPart[];
};

export type Category = { id: string; name: string; slug: string; description: string | null; sortOrder: number; isActive: boolean; articleCount: number };
export type Tag = { id: string; name: string; slug: string; description: string | null; articleCount: number };
export type Series = { id: string; name: string; slug: string; description: string | null; coverImageId: string | null; articleCount: number };
export type SeriesDetail = { id: string; name: string; slug: string; description: string | null; articles: { id: string; title: string; slug: string; order: number | null; status: string; publishedAt: string | null }[] };
export type Author = { id: string; displayName: string; slug: string; bio: string; avatarUrl: string | null; gitHubUrl: string | null; linkedInUrl: string | null; xUrl: string | null; websiteUrl: string | null; articleCount: number };
export type SiteSettings = { siteName: string; siteDescription: string; siteUrl: string; logoUrl: string; faviconUrl: string; defaultAuthorSlug: string; publishingMode: string; social: { gitHub: string | null; linkedIn: string | null; x: string | null; youTube: string | null } };
export type AnalyticsSummary = {
  totalArticles: number;
  published: number;
  drafts: number;
  scheduled: number;
  pendingReview: number;
  aiGenerated: number;
  totalViews: number;
  topArticles: ArticleListItem[];
  recentArticles: ArticleListItem[];
  upcoming: { id: string; title: string; slug: string; status: string; at: string | null }[];
  viewsByDay: { date: string; views: number }[];
};
export type AgentCredential = {
  id: string;
  name: string;
  keyPrefix: string;
  scopes: string[];
  status: string;
  createdAt: string;
  expiresAt: string | null;
  lastUsedAt: string | null;
  lastAction: string | null;
};
export type AuditLog = {
  id: string;
  actorId: string;
  actorType: string;
  actorName: string;
  action: string;
  resourceType: string;
  resourceId: string | null;
  timestamp: string;
  ipAddress: string | null;
  requestId: string | null;
  metadataJson: string | null;
};
export type AuthResponse = {
  accessToken: string;
  refreshToken: string;
  expiresAt: string;
  user: { id: string; email: string; displayName: string; roles: string[]; authorId: string | null };
};
export type ValidationResult = {
  valid: boolean;
  readyToPublish: boolean;
  score: number;
  seoScore: number;
  contentScore: number;
  errors: { code: string; message: string; severity: string }[];
  warnings: { code: string; message: string; severity: string }[];
  missingMetadata: string[];
};
export type MediaAsset = {
  id: string;
  fileName: string;
  url: string;
  mimeType: string;
  fileSize: number;
  width: number | null;
  height: number | null;
  altText: string | null;
  title: string | null;
  description: string | null;
  createdAt: string;
};
